[Sanity] in_ch=8 (2*C), F=256, Tseg=184. Batch sizes: mixture_2ft=(8, 8, 256, 184), cirm_2ft=(8, 2, 256, 184)
Exception in thread Thread-4 (_pin_memory_loop):
Traceback (most recent call last):
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 53, in _pin_memory_loop
    do_one_step()
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 30, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/site-packages/torch/multiprocessing/reductions.py", line 495, in rebuild_storage_fd
    fd = df.detach()
         ^^^^^^^^^^^
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/multiprocessing/connection.py", line 501, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/multiprocessing/connection.py", line 629, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/data1/is156025/zb276885/LMFCA-Net/train.py", line 202, in <module>
    train(args)
  File "/data1/is156025/zb276885/LMFCA-Net/train.py", line 144, in train
    train_loss += train_one_batch(
                  ^^^^^^^^^^^^^^^^
  File "/data1/is156025/zb276885/LMFCA-Net/train.py", line 48, in train_one_batch
    loss.backward()
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/local/home/zb276885/miniforge3/envs/tango_env/lib/python3.11/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
